### PR TITLE
Add venv files to .gitignore

### PR DESCRIPTION
**Pull request by GregShiner**
### Long story short
Add files and directories related to virtual envs to the .gitignore file.

### Checks

- `[x]` I have run `nox` tests and all tests have passed.

### CODE REVIEW

**Comment by gman1230321** [comment]
- .venv and venv are the folders for unix/linux based systems, but its Scripts and Lib on windows I believe. That's why those are there.
- I'll try that fix.
- I believe it was left there because I accidentally aborted one of the tests and it didn't delete the file.

**Comment by nxtlo** [comment]
Not really. What i meant is the `.venv` and `venv` are just the most common venv names you'll find in Python projects whether its Unix sys or Windows, That's why most people just ignore those names. So you should just recreate a venv with one of those names.

I fixed for the client_test pipeline [here](https://github.com/nxtlo/aiobungie/blob/3e16b02e7516377b834fa1c31bd7f4f9b17f71ba/nix/clienttest-nox.py#L29). Well eventually get merged later.

**Comment by gman1230321** [comment]
I don't really care, it's not a big deal and up to you.

**Comment by nxtlo** [comment]
I get it @leoericson I use windows for development myself. The `Lib` and `Scripts` folders are generated inside the `.venv` folder which's why im only ignoring that. Both Lib and Scripts folders will get ignored since they're inside `.venv` so i don't really see whats the issue here? any ways im closing this for now.

**Pull request closed without merging**
